### ISSUE TITLE
Add back in the 'live' indicator on the schedule

### ISSUE THREAD

**Issue by jamesturner** [URN/URN-Material#23]
Removed in 4a5ebaf842498dfa67268254aada15a52801d597 in order to concentrate on other more important issues before the start of term.

**Comment by johnathan99j** [comment]
Is this just a marker to show that the show's active and if so does the current 'ON AIR' marker do the job?

**Comment by harrymt** [comment]
@johnathan99j yeah, it was just a line that marks the current time. I don't think this is necessary anymore, because we have the Listen Now text.
