### ISSUE TITLE
Implement caching

### ISSUE THREAD

**Issue by jamesturner** [URN/URN-Material#31]
Find a way to cache pages to save on processing and bandwidth. Especially some of the API endpoints which are hit very frequently but who's output only changes at set times.

**Comment by johnathan99j** [comment]
Is counted as done due to the move to the new server and the caching that you implemented @jamesturner ?

**Comment by jamesturner** [comment]
Yep I reckon so, we also use the [W3 Total Cache](https://en-gb.wordpress.org/plugins/w3-total-cache/) wordpress plugin to cache and minify some resources as well.

Closed in ff13369cb83b34b103feb7489b2f2eaf788701af.
