### ISSUE TITLE
Footer breaks in IE 8.0 up to 11.0

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#33]
Footer stays at the top, meaning white wrapper isn't pushed to the bottom e.g. in IE 11.0
![screen shot 2015-09-10 at 12 41 07](https://cloud.githubusercontent.com/assets/5204061/9787460/f3c26a04-57ba-11e5-8fd2-5e4ed575c81a.png)

**Comment by johnathan99j** [comment]
Due to the demographic of our site I'd say that support for IE isn't something we need to really worry about especially since usage of IE is dropping globally.
