### ISSUE TITLE
Change admin password for security

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#40]
The admin password was shared for simplicity of use, but from now on users will have their own username & password, so the admin password should be changed to prevent others using it.

**Comment by johnathan99j** [comment]
Did this happen ?

**Comment by harrymt** [comment]
Unsure. @jamesturner do you remember if we changed the password after the committee had finished using it - to easily change things?

**Comment by jamesturner** [comment]
Don't think so actually, might be worth doing so.

**Comment by johnathan99j** [comment]
:+1:
