### ISSUE TITLE
Finish the styling for the shows page

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#41]
Add some CSS styles to the shows page, to make it look less bland

**Comment by johnathan99j** [comment]
I take it by finish you mean add some degree of styling ? :joy:

**Comment by harrymt** [comment]
@johnathan99j Sorry, I did not write up this issue at all! The main thoughts were styling, mainly because we were pushed for release and ran out of time with this!

**Comment by johnathan99j** [comment]
Nothing fancy but it at least fits with the regular theme. Asked a few in the studio and they liked it. Thoughts ? 
![temp](https://cloud.githubusercontent.com/assets/15066398/15085415/182dccac-13d2-11e6-8267-aad955c16b00.png)

**Comment by jamesturner** [comment]
Looks good, only thing I would suggest is changing the heading colour from purple to black (#272727/$body-text-color in scss) in order to stay in line with of the existing headings on the site (competitions page, get involved page etc.)

**Comment by johnathan99j** [comment]
Closed by 333c421

**Comment by johnathan99j** [comment]
Also 6af6ffb
