### ISSUE TITLE
Add slogan to header 'Your Music. Your News. Your Student Sound.'

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#45]
Note only if not too long after font change.

**Comment by johnathan99j** [comment]
Is dependent on #42

**Comment by johnathan99j** [comment]
Thoughts for #71 ? 
![temp](https://cloud.githubusercontent.com/assets/15066398/14622495/2b1029d2-05c2-11e6-87ab-a6f96c5ab7d0.png)

**Comment by harrymt** [comment]
I think there is a typo in the issue. I believe the slogan should read 'Your Music. Your news. Your Student Sound.'

**Comment by johnathan99j** [comment]
Closed with  de593ac

**Comment by johnathan99j** [comment]
Note: Mobile scss is still worth looking at

**Comment by johnathan99j** [comment]
Broke layout on the web server, works fine on my end and seemed to on @jamesturner's laptop, @harrymt can you check it on yours? 
Should look like this.
![temp](https://cloud.githubusercontent.com/assets/15066398/14644797/3e0e55ac-064b-11e6-8a91-7697ceb46e53.png)

**Comment by harrymt** [comment]
@johnathan99j The main issues with this subtitle are when the design is viewed at different screen sizes.

The website needs to have a responsive design, so people viewing the site on a mobile, or a tablet, can have the same or similar experience when viewing the desktop site.

The screenshots here, illustrate how this breaks the design when viewed on a mobile and tablet.

**Tablet**

![13022380_10153717154119527_68598136_n](https://cloud.githubusercontent.com/assets/5204061/14676043/a7fe65e8-0703-11e6-9907-f3c828e8c050.jpeg)

**Mobile**

![13045395_10153717154124527_238426399_n](https://cloud.githubusercontent.com/assets/5204061/14676042/a7fcd61a-0703-11e6-9712-5e7cddfb2a1d.png)

**Comment by johnathan99j** [comment]
Closed by 98f39ee and actually fixed this time, I even learnt something :smile:
