### ISSUE TITLE
Restyle competitions as there is too much whitespace

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#49]
Perhaps try:

- Adding gallery images
- Creating its own template and using a 3 column style

**Comment by johnathan99j** [comment]
So I had a look and 2/3 of the competitions on there have expired, is someone working on getting new ones or should we just re write to just have the active one there and work around that one ?

**Comment by harrymt** [comment]
@johnathan99j the marketing section of URN are responsible for this page and I think we have not had many competitions this year, so this page hasn't been updated much. The re-style of this page is probably a low priority issue for now.

**Comment by johnathan99j** [comment]
Fair enough.
