### ISSUE TITLE
Complete Podcasts page

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#5]
## Things to do

- [x] Force all shows to use AudioBoom by just getting podcasts from AudioBoom channels, use speech atm https://audioboom.com/channel/URNspeech

**Comment by johnathan99j** [comment]
What did you mean by "create these" @harrymt ?

**Comment by harrymt** [comment]
@johnathan99j sorry, this is a very old issue that occurred when we had 0 podcast content on AudioBoom. But we have content now and so is resolved!
