### ISSUE TITLE
Make the blogs page more 'fancy'.

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#50]
Perhaps try

-  Excerpts with images?

**Comment by johnathan99j** [comment]
Helped a little by 58465bb.

**Comment by harrymt** [comment]
@johnathan99j although this does reduce the length of the page. It hurts the user experience of the page as nested scroll elements confuse users when they expect to be scrolling the page, but are instead, scrolling inside another element. This is also affected on a mobile device.

Instead of this, using Wordpress PHP commands, any images used on a blog post can be extracted from a post and used to describe each post in the list, making the blogs page, more 'fancy'.
