### ISSUE TITLE
Add pagination to blogs page

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#61]

**Comment by johnathan99j** [comment]
Closed by 2e275d2.

**Comment by jamesturner** [comment]
I think the aim here was to split the blogs across many pages, Wordpress [supports this](https://codex.wordpress.org/Pagination) rather than just scrolling the container

**Comment by johnathan99j** [comment]
Ah right I see now, not sure how that'd work with the current setup.

**Comment by johnathan99j** [comment]
Closed by c096b01. For real this time :stuck_out_tongue_closed_eyes:
