### ISSUE TITLE
Having current committee on 'About Us'

### ISSUE THREAD

**Issue by johnathan99j** [URN/URN-Material#74]
It would require some degree of upkeep like once a year but that shouldn't be a problem, I'm thinking individual pictures with role title and a short bio ?

**Comment by thomas-** [comment]
sorry gonna chip in here, this comes up a lot!

i'd advise against it, it looks amateur-y and ultimately no listener or someone who visits the site cares who the head of marketing is. i think personability is important for someone looking to get involved, eg having names on the get involved page works well but bios are yucky

lots of other student stations do it (actually i've given this advice to many of them) and it always looks awkward

**Comment by johnathan99j** [comment]
You've got a point about listeners not really caring but I think for people looking to join having a section of committee pictures and names would be a nice addition, granted the bios might be a little over the top. I'm not thing of making this a major feature just something else tacked on the the page, maybe even just a group photo or something ?

**Comment by harrymt** [comment]
@johnathan99j We discussed this with Iona Hampson (head of marketing) and we decided against adding this in, mainly because of the reasons @thomas- said above.

**Comment by johnathan99j** [comment]
:+1:
