### ISSUE TITLE
Song titles can overflow the window.

### ISSUE THREAD

**Issue by johnathan99j** [URN/URN-Material#76]
![temp](https://cloud.githubusercontent.com/assets/15066398/15277044/e3ecfbae-1af0-11e6-98cf-dc929753584b.png)

**Comment by jamesturner** [comment]
Probably best to hide the overflow on the container and use [`text-overflow: ellipsis`](https://developer.mozilla.org/en/docs/Web/CSS/text-overflow) to make it look nice.

**Comment by johnathan99j** [comment]
Yer, got half a commit on my pc. Working on having it scroll sideways when hovered over so you can still read it all.

**Comment by johnathan99j** [comment]
Closed by a5c6476. I decided against scrolling.
