### ISSUE TITLE
Avoid long show time strings on show pages

### ISSUE THREAD

**Issue by jamesturner** [URN/URN-Material#77]
On pages like [The Pulse](http://urn1350.net/show/the-pulse/) with almost daily shows, the slot times make an ugly/repetitive string.

Build the string more intelligently. The Pulse's show page instead of saying:

> Mondays from 5:00pm, Tuesdays from 5:00pm, Wednesdays from 5:00pm, Thursdays from 5:00pm, Fridays from 5:00pm

will be...

> Mondays, Tuesdays, Wednesdays, Thursdays, Fridays from 5:00pm

or 

> Weekdays from 5:00pm

Possible pseudocode:

```
group slots based on start time

for each of those groups (e.g. 5:00, 19:00) {
    if show has multiple DIFFERENT slots for a certain day {
        continue;
    }
    
    if (group.slots.length == 5 && group.slots.contain([monday,tuesday,wednesday,thursday,friday]) {
        string = "Weekdays from <TIME>"
    }
    else {
        string = "<DAYNAME>s, <DAYNAME>s, <DAYNAME>s from <TIME>"
    }
}

```

**Comment by johnathan99j** [comment]
The commas are a little iffy, will look into them when I have time.
