### ISSUE TITLE
Complete Listen Now player

### ISSUE THREAD

**Issue by harrymt** [URN/URN-Material#8]
## Things to do

- [x] Link web message, need to get this working before freshers!
- [x] Add that you can also tweet & text this number 07762 212 434
- [x] Link player, can test this after station is switched on

**Comment by johnathan99j** [comment]
Closed by 14466f5

**Comment by harrymt** [comment]
@johnathan99j looks good man! However, the text for the 'shrink'/'expand' button is cut off on iPhone 5s chrome mobile and safari mobile. 
![image](https://cloud.githubusercontent.com/assets/5204061/15244642/fda17244-18f9-11e6-9c8c-a1bf5c7ae460.png)
