### ISSUE TITLE
May I get dummy content of http://urn1350.net/

### ISSUE THREAD

**Issue by lovebdsobuj** [URN/URN-Material#80]
Hi,

**`URN-Material`** is a very nice WP theme!

May I get dummy content of http://urn1350.net/?

**Comment by johnathan99j** [comment]
Hi,

I'm glad you like the theme! The majority of the content is just created inside wordpress as a page, the rest is created as a blank page with a template that holds the content, these can be found in the root directory. 

I'm afraid there's no dummy content really available. I'd suggest making some pages with some Lorem Ipsum and basic images.

**Comment by lovebdsobuj** [comment]
@johnathan99j You're right absolutely I realized it after using your theme.

What about send message?

May I get `live send message` script, locate is here http://int.urn1350.net/web/

**Comment by johnathan99j** [comment]
That script is more of an internal script and not one that I will share, everything that is on GitHub is all our open source stuff, if it's not on GitHub then it's closed source.

The general gist is that it parse's the input and moves it on through our system.

**Comment by lovebdsobuj** [comment]
Okay @johnathan99j, your pleasure.

But I will be glad if **`URN`** GitHub stuff share it with me at least privately. 
Actually I want to Stand a website using `URN-Material` theme without live send message option site looks immature.
